
package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.725+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "fault7", targetNamespace = "http://pep.base.nmsf.csi.it/")
public class CertRevokedException_Exception extends Exception {

    private it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.CertRevokedException fault7;

    public CertRevokedException_Exception() {
        super();
    }

    public CertRevokedException_Exception(String message) {
        super(message);
    }

    public CertRevokedException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public CertRevokedException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.CertRevokedException fault7) {
        super(message);
        this.fault7 = fault7;
    }

    public CertRevokedException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.CertRevokedException fault7, java.lang.Throwable cause) {
        super(message, cause);
        this.fault7 = fault7;
    }

    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.CertRevokedException getFaultInfo() {
        return this.fault7;
    }
}
