
package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.681+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "fault8", targetNamespace = "http://pep.base.nmsf.csi.it/")
public class IdentitaNonAutenticaException_Exception extends Exception {

    private it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentitaNonAutenticaException fault8;

    public IdentitaNonAutenticaException_Exception() {
        super();
    }

    public IdentitaNonAutenticaException_Exception(String message) {
        super(message);
    }

    public IdentitaNonAutenticaException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IdentitaNonAutenticaException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentitaNonAutenticaException fault8) {
        super(message);
        this.fault8 = fault8;
    }

    public IdentitaNonAutenticaException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentitaNonAutenticaException fault8, java.lang.Throwable cause) {
        super(message, cause);
        this.fault8 = fault8;
    }

    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentitaNonAutenticaException getFaultInfo() {
        return this.fault8;
    }
}
