
package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.700+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "fault4", targetNamespace = "http://pep.base.nmsf.csi.it/")
public class IdProviderNotFoundException_Exception extends Exception {

    private it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdProviderNotFoundException fault4;

    public IdProviderNotFoundException_Exception() {
        super();
    }

    public IdProviderNotFoundException_Exception(String message) {
        super(message);
    }

    public IdProviderNotFoundException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public IdProviderNotFoundException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdProviderNotFoundException fault4) {
        super(message);
        this.fault4 = fault4;
    }

    public IdProviderNotFoundException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdProviderNotFoundException fault4, java.lang.Throwable cause) {
        super(message, cause);
        this.fault4 = fault4;
    }

    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdProviderNotFoundException getFaultInfo() {
        return this.fault4;
    }
}
