
package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.706+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "fault5", targetNamespace = "http://pep.base.nmsf.csi.it/")
public class MalformedUsernameException_Exception extends Exception {

    private it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.MalformedUsernameException fault5;

    public MalformedUsernameException_Exception() {
        super();
    }

    public MalformedUsernameException_Exception(String message) {
        super(message);
    }

    public MalformedUsernameException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public MalformedUsernameException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.MalformedUsernameException fault5) {
        super(message);
        this.fault5 = fault5;
    }

    public MalformedUsernameException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.MalformedUsernameException fault5, java.lang.Throwable cause) {
        super(message, cause);
        this.fault5 = fault5;
    }

    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.MalformedUsernameException getFaultInfo() {
        return this.fault5;
    }
}
