package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.743+01:00
 * Generated source version: 3.3.2
 *
 */
@WebServiceClient(name = "PolicyEnforcerBaseService",
                  wsdlLocation = "http://tst-applogic-nmsf2e.csi.it/pep_wsfad_nmsf_policy/services/PolicyEnforcerBase?wsdl",
                  targetNamespace = "http://pep.base.nmsf.csi.it/")
public class PolicyEnforcerBaseService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://pep.base.nmsf.csi.it/", "PolicyEnforcerBaseService");
    public final static QName PolicyEnforcerBase = new QName("http://pep.base.nmsf.csi.it/", "PolicyEnforcerBase");
    static {
        URL url = null;
        try {
            url = new URL("http://tst-applogic-nmsf2e.csi.it/pep_wsfad_nmsf_policy/services/PolicyEnforcerBase?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PolicyEnforcerBaseService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://tst-applogic-nmsf2e.csi.it/pep_wsfad_nmsf_policy/services/PolicyEnforcerBase?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PolicyEnforcerBaseService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PolicyEnforcerBaseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyEnforcerBaseService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public PolicyEnforcerBaseService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PolicyEnforcerBaseService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PolicyEnforcerBaseService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns PolicyEnforcerBase
     */
    @WebEndpoint(name = "PolicyEnforcerBase")
    public PolicyEnforcerBase getPolicyEnforcerBase() {
        return super.getPort(PolicyEnforcerBase, PolicyEnforcerBase.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyEnforcerBase
     */
    @WebEndpoint(name = "PolicyEnforcerBase")
    public PolicyEnforcerBase getPolicyEnforcerBase(WebServiceFeature... features) {
        return super.getPort(PolicyEnforcerBase, PolicyEnforcerBase.class, features);
    }

}
