package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.732+01:00
 * Generated source version: 3.3.2
 *
 */
@WebService(targetNamespace = "http://pep.base.nmsf.csi.it/", name = "PolicyEnforcerBase")
@XmlSeeAlso({ObjectFactory.class})
public interface PolicyEnforcerBase {

    @WebMethod
    @RequestWrapper(localName = "isPersonaInRuolo", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IsPersonaInRuolo")
    @ResponseWrapper(localName = "isPersonaInRuoloResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IsPersonaInRuoloResponse")
    @WebResult(name = "isPersonaInRuoloReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public boolean isPersonaInRuolo(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Ruolo in1
    ) throws InternalException_Exception, SystemException_Exception, BadRuoloException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findActorsForPersonaInUseCase", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindActorsForPersonaInUseCase")
    @ResponseWrapper(localName = "findActorsForPersonaInUseCaseResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindActorsForPersonaInUseCaseResponse")
    @WebResult(name = "findActorsForPersonaInUseCaseReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.util.List<it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Actor> findActorsForPersonaInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, NoSuchUseCaseException_Exception, SystemException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "identificaUserPassword", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentificaUserPassword")
    @ResponseWrapper(localName = "identificaUserPasswordResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentificaUserPasswordResponse")
    @WebResult(name = "identificaUserPasswordReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita identificaUserPassword(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        java.lang.String in1
    ) throws InternalException_Exception, IdProviderNotFoundException_Exception, MalformedUsernameException_Exception, AuthException_Exception, SystemException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "identificaUserPasswordPIN", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentificaUserPasswordPIN")
    @ResponseWrapper(localName = "identificaUserPasswordPINResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentificaUserPasswordPINResponse")
    @WebResult(name = "identificaUserPasswordPINReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita identificaUserPasswordPIN(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        java.lang.String in1,
        @WebParam(name = "in2", targetNamespace = "http://pep.base.nmsf.csi.it/")
        java.lang.String in2
    ) throws InternalException_Exception, IdProviderNotFoundException_Exception, MalformedUsernameException_Exception, AuthException_Exception, SystemException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findRuoliForPersonaInUseCase", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindRuoliForPersonaInUseCase")
    @ResponseWrapper(localName = "findRuoliForPersonaInUseCaseResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindRuoliForPersonaInUseCaseResponse")
    @WebResult(name = "findRuoliForPersonaInUseCaseReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.util.List<it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Ruolo> findRuoliForPersonaInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, NoSuchUseCaseException_Exception, SystemException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findRuoliForPersonaInApplication", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindRuoliForPersonaInApplication")
    @ResponseWrapper(localName = "findRuoliForPersonaInApplicationResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindRuoliForPersonaInApplicationResponse")
    @WebResult(name = "findRuoliForPersonaInApplicationReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.util.List<it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Ruolo> findRuoliForPersonaInApplication(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Application in1
    ) throws InternalException_Exception, SystemException_Exception, NoSuchApplicationException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findActorsForPersonaInApplication", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindActorsForPersonaInApplication")
    @ResponseWrapper(localName = "findActorsForPersonaInApplicationResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindActorsForPersonaInApplicationResponse")
    @WebResult(name = "findActorsForPersonaInApplicationReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.util.List<it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Actor> findActorsForPersonaInApplication(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Application in1
    ) throws InternalException_Exception, SystemException_Exception, NoSuchApplicationException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isPersonaAutorizzataInUseCase", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IsPersonaAutorizzataInUseCase")
    @ResponseWrapper(localName = "isPersonaAutorizzataInUseCaseResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IsPersonaAutorizzataInUseCaseResponse")
    @WebResult(name = "isPersonaAutorizzataInUseCaseReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public boolean isPersonaAutorizzataInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, NoSuchUseCaseException_Exception, SystemException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "findUseCasesForPersonaInApplication", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindUseCasesForPersonaInApplication")
    @ResponseWrapper(localName = "findUseCasesForPersonaInApplicationResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.FindUseCasesForPersonaInApplicationResponse")
    @WebResult(name = "findUseCasesForPersonaInApplicationReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.util.List<it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UseCase> findUseCasesForPersonaInApplication(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Application in1
    ) throws InternalException_Exception, SystemException_Exception, NoSuchApplicationException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getInfoPersonaSchema", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.GetInfoPersonaSchema")
    @ResponseWrapper(localName = "getInfoPersonaSchemaResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.GetInfoPersonaSchemaResponse")
    @WebResult(name = "getInfoPersonaSchemaReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.lang.String getInfoPersonaSchema(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Ruolo in0
    ) throws InternalException_Exception, SystemException_Exception, BadRuoloException_Exception, UnrecoverableException_Exception;

    @WebMethod
    @RequestWrapper(localName = "getInfoPersonaInUseCase", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.GetInfoPersonaInUseCase")
    @ResponseWrapper(localName = "getInfoPersonaInUseCaseResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.GetInfoPersonaInUseCaseResponse")
    @WebResult(name = "getInfoPersonaInUseCaseReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public java.lang.String getInfoPersonaInUseCase(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0,
        @WebParam(name = "in1", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UseCase in1
    ) throws InternalException_Exception, NoSuchApplicationException_Exception, NoSuchUseCaseException_Exception, SystemException_Exception, UnrecoverableException_Exception, IdentitaNonAutenticaException_Exception;

    @WebMethod
    @RequestWrapper(localName = "identificaCertificato", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentificaCertificato")
    @ResponseWrapper(localName = "identificaCertificatoResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IdentificaCertificatoResponse")
    @WebResult(name = "identificaCertificatoReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita identificaCertificato(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        byte[] in0
    ) throws InternalException_Exception, IdProviderNotFoundException_Exception, SystemException_Exception, CertOutsideValidityException_Exception, UnrecoverableException_Exception, CertRevokedException_Exception;

    @WebMethod
    @RequestWrapper(localName = "isIdentitaAutentica", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IsIdentitaAutentica")
    @ResponseWrapper(localName = "isIdentitaAutenticaResponse", targetNamespace = "http://pep.base.nmsf.csi.it/", className = "it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.IsIdentitaAutenticaResponse")
    @WebResult(name = "isIdentitaAutenticaReturn", targetNamespace = "http://pep.base.nmsf.csi.it/")
    public boolean isIdentitaAutentica(

        @WebParam(name = "in0", targetNamespace = "http://pep.base.nmsf.csi.it/")
        it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.Identita in0
    ) throws InternalException_Exception, SystemException_Exception, UnrecoverableException_Exception;
}
