
package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.661+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "fault1", targetNamespace = "http://pep.base.nmsf.csi.it/")
public class SystemException_Exception extends Exception {

    private it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.SystemException fault1;

    public SystemException_Exception() {
        super();
    }

    public SystemException_Exception(String message) {
        super(message);
    }

    public SystemException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public SystemException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.SystemException fault1) {
        super(message);
        this.fault1 = fault1;
    }

    public SystemException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.SystemException fault1, java.lang.Throwable cause) {
        super(message, cause);
        this.fault1 = fault1;
    }

    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.SystemException getFaultInfo() {
        return this.fault1;
    }
}
