
package it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2020-12-21T09:41:23.674+01:00
 * Generated source version: 3.3.2
 */

@WebFault(name = "fault", targetNamespace = "http://pep.base.nmsf.csi.it/")
public class UnrecoverableException_Exception extends Exception {

    private it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UnrecoverableException fault;

    public UnrecoverableException_Exception() {
        super();
    }

    public UnrecoverableException_Exception(String message) {
        super(message);
    }

    public UnrecoverableException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UnrecoverableException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UnrecoverableException fault) {
        super(message);
        this.fault = fault;
    }

    public UnrecoverableException_Exception(String message, it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UnrecoverableException fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public it.csi.myprod.myprodsrvqrk.api.wsclient.iride2pep.UnrecoverableException getFaultInfo() {
        return this.fault;
    }
}
